language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
matrix:
    fast_finish: true
    # command to install dependencies
install:
    - pip install requests
    - pip install pytest
    - pip install coverage
    - pip install coveralls
    - python setup.py install
    # command to run tests
script:
    - coverage run --source=pbwrap -m pytest
    - coverage report
    - coveralls
branches:
    only:
        - master
        - dev
