language: python
python:
    - "3.5"
    - "3.5-dev"  # 3.5 development branch
    - "3.6"
    - "3.6-dev"  # 3.6 development branch

matrix:
    fast_finish: true
    allow_failures:
        -python: 3.6-dev
        -python: 3.5-dev
    # command to install dependencies
install:
    - pip install requests
    - pip install pytest
    - pip install coverage
    - pip install coveralls
    - python setup.py install
    # command to run tests
script:
    - coverage run --source=pbwrap -m pytest
    - coverage report
    - coveralls
